# Generated by Django 4.1.7 on 2023-02-21 12:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="uploaded_by",
            field=models.CharField(default=account.models.CustomUser, max_length=100),
        ),
    ]
