# Generated by Django 4.0.3 on 2023-02-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pen_name',
        ),
    ]
