# Generated by Django 4.0.3 on 2023-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_profile_picture_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x000001D019E60880>/'),
        ),
    ]
