# Generated by Django 4.0.3 on 2023-02-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/default.png', max_length=500, upload_to='profile_pictures/users/'),
        ),
    ]
